name: geolayout
dependencies:
- python>=3.7
- pip
- pip:
  - torch=1.6.0
  - numpy=1.19.1
  - h5py=2.10.0
  - pandas=1.1.0
  - scipy=1.5.2
  - torchvision=0.7.0
  - Pillow=8.2.0
  - scikit_learn=0.24.1
